### ISSUE TITLE
[BUG] Shuffle button missing for different UI version of YouTube

### ISSUE THREAD

**Issue by jcapinc** [NikkelM/Random-YouTube-Video#101]
UI change on Youtube's part made shuffle button disappear on video player UI.

1. Go to a Channel
2. Click "Shuffle" button added by plugin on the videos
3. Look for and Fail to find Shuffle Button below played youtube video

Expected find button to shuffle videos below video element and controles on youtube's video screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1325626/225208660-1c83bde8-b1e8-4160-9ce9-dc7bfb812ba7.png)

**Software information(please complete the following information):**
 - Extension Version 1.2.1:
 - Brave v1.49.120:

**Comment by NikkelM** [comment]
Thanks for the report.
It looks like YouTube is rolling out this new UI to a few new users, as I'm not able to reproduce this with the browser version you provided. As I'll need to be able to find out which UI elements changed in what way, I unfortunately can't resolve this right now, but will of course keep a look out.
As a workaround, I'll be working on adding a shuffle button to the popup, which should make it possible to use the extension even when YouTube changes the UI like this. I'll let you know in this issue when that functionality has been released.

**Comment by NikkelM** [comment]
Closed due to inactivity.
