### ISSUE TITLE
ANDROID

### ISSUE THREAD

**Issue by Autounit777** [NikkelM/Random-YouTube-Video#132]
**Is your feature request related to a problem? Please describe.**

I would love to see your application on Android devices. Do you have such plans in the near future?

**Comment by NikkelM** [comment]
Hi @Autounit777, 
no, at the moment I'm not planning on building an Android app for this, as that would require a significant amount of work aside from the extension functionality itself.
If you want to use the extension on Android, you could however try and install a browser that supports Chrome extensions and check if the extension perhaps works on your mobile device as well that way - I unfortunately cannot check this myself right now, as I don't have access to an Android device.
Sorry the answer couldn't be more positive!

**Comment by Autounit777** [comment]
thanks for the quick response your app is amazing
