### ISSUE TITLE
[FEATURE] add random videos on main youtube page

### ISSUE THREAD

**Issue by shinji2009** [NikkelM/Random-YouTube-Video#275]
hi
can you make extention to make all videos on main youtube completley random? not only from one channel or subscriptions. just literally absolutely random videos. 

i ask because youtube just keep showing me newest hype not interetring garbage, althoug it knows what i like and know what in my subscriptions is something absolutely different

**Comment by NikkelM** [comment]
Hi - I get the sentiment, and I agree that YouTube recommendations aren't what they used to be. Unfortunately, adding that functionality is not very feasible, as the way the extension can interact with the YouTube API (where it gets video information from) is not able to get totally random videos. There's some websites out there that try to emulate the feeling of totally random videos, but they are also restricted by this, so will not be completely random.
Sorry I couldn't give a more positive answer.
