### ISSUE TITLE
[BUG/FEATURE] End 'Access browser tabs' permission ambiguity

### ISSUE THREAD

**Issue by OutshineIssue** [NikkelM/Random-YouTube-Video#320]
**Describe the bug**
The add-on requests the "Access browser tabs" permission, which I believe is primarily for the "reuse new tab" feature. However, this permission feels quite excessive and raises concerns for what is essentially a simple and optional feature for an add-on that really only works on YouTube.

The Firefox store description lists this permission as both mandatory and optional, which is quite confusing:

![image](https://github.com/user-attachments/assets/3626fa8f-9a8f-417b-95bf-98a7b959094b)

It seems there may have been an attempt to make this permission optional, but the ambiguity in the store listing could be due to a miswritten manifest bug or a similar issue.

**Describe the solution you'd like**
I'm not asking for its removal, since many users might find the reuse new tab feature useful. However, I would like for users who do not have that option toggled to be exempt from the permission requirement.

I would like to see the "Access browser tabs" permission made 100% optional, without the ambiguity presented in the store. It would be more user-friendly to allow users to choose whether they want to enable that feature and grant the permission accordingly. This way, those who prefer not to use that option can still enjoy the core functionality of the add-on without unnecessary permission concerns.

**Additional context**
Clarifying the permissions and making the tab access optional would enhance user trust and privacy, especially since many users are cautious about granting permissions that aren’t essential for the main features of an add-on. The current ambiguity in the store description could lead to confusion, and addressing this would improve the overall user experience.

**Comment by NikkelM** [comment]
Thanks for the report - I'm not sure why the store page for Firefox shows the permissions like this, but I will be taking a look at what's the best way of resolving this.

**Comment by NikkelM** [comment]
You were right - the `tabs` permission was specified in both the common manifest, and the additional firefox manifest, which caused this duplication on the store page.
I have also been able to remove the need for the `tabs` permission as a whole by refactoring some code and redefining the host permissions to youtube.com, so this will be removed with the next version.
The only downside is that some Quality of Life in the chromium version of the extension no longer functions (mostly related to not having multiple versions of the same extension-internal pages like the changelog open at once), but that's a good trade-off to take.

**Comment by NikkelM** [comment]
Funnily enough, it seems the reworked permissions structure has resulted in the "access to the youtube.com domain" permission to be shown in both the required and optional sections - but I think that is not something I can resolve at this point.
