### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Autounit777** [NikkelM/Random-YouTube-Video#40]
HELLO FRIEND talented developer, I need your help.
the world of longplay channel https://www.youtube.com/@worldoflongplays has 16000 videos. your program worked. BUT the Kuplinov Play channel https://www.youtube.com/@kuplinovplay has 6000 videos and the program failed. tried 4 times. waited a long time, more than an hour and two hours. The channel has 14 million subscribers. HELP PLEASE

**Comment by NikkelM** [comment]
Hi @Autounit777, I'm sorry to hear that - it sounds like something broke inside the extension while fetching the videos, as such long waiting times are not normal at all. For a channel of 6000 videos that is accessed the first time, it should be about 20 seconds at most.
I used the extension on the two channels you linked, and it worked both times, so it may be linked to the local data saved in your browser being corrupted. I've just refreshed the channel's information in the backend database as well, in case it was linked to that.

I have two suggestions:
1. Simply try again once more now, perhaps the reset in the database resolved your issue. In case that it still does not work, the following information might help me track down the issue:
- Which browser you are using the extension on
- When you open the developer tools of your browser (most times by pressing F12) while on the channel page, if you take a look at the "Console" tab, you will see the extension output logs when you press the "Random" button. If there is an internal issue, the extension will log it here. All extension logs are prefixed by `[youtube-random-video]`, so you should be able to easily identify them.
- Alternatively to the step above, if turned on, you should be able to see any errors the extension has produced if you go to your browser's list of extensions, and look at the "Details" page for the extension.

2. The other approach would be to un- an reinstall the extension. This clears the locally saved data, which may be corrupted. I will also try to make this possible using the extension itself in a future version.

I hope this gets your issue resolved, feel free to get back to me with any data or other questions.

**Comment by Autounit777** [comment]
> Hi @Autounit777, I'm sorry to hear that - it sounds like something broke inside the extension while fetching the videos, as such long waiting times are not normal at all. For a channel of 6000 videos that is accessed the first time, it should be about 20 seconds at most. I used the extension on the two channels you linked, and it worked both times, so it may be linked to the local data saved in your browser being corrupted. I've just refreshed the channel's information in the backend database as well, in case it was linked to that.
> 
> I have two suggestions:
> 
> 1. Simply try again once more now, perhaps the reset in the database resolved your issue. In case that it still does not work, the following information might help me track down the issue:
> 
> * Which browser you are using the extension on
> * When you open the developer tools of your browser (most times by pressing F12) while on the channel page, if you take a look at the "Console" tab, you will see the extension output logs when you press the "Random" button. If there is an internal issue, the extension will log it here. All extension logs are prefixed by `[youtube-random-video]`, so you should be able to easily identify them.
> * Alternatively to the step above, if turned on, you should be able to see any errors the extension has produced if you go to your browser's list of extensions, and look at the "Details" page for the extension.
> 
> 2. The other approach would be to un- an reinstall the extension. This clears the locally saved data, which may be corrupted. I will also try to make this possible using the extension itself in a future version.
> 
> I hope this gets your issue resolved, feel free to get back to me with any data or other questions.



now everything is working. You are an amazing developer and are quick to help solve a problem. Huge thanks to you. good luck.

**Comment by NikkelM** [comment]
Great to hear - so it was probably the data in the backend database that caused the problem. Glad to hear it works now, have fun!
