### ISSUE TITLE
[FEATURE] Add setting to run videos as non playlist.

### ISSUE THREAD

**Issue by scolastico** [NikkelM/Random-YouTube-Video#66]
**Is your feature request related to a problem? Please describe.**
I think it would be a great feature if I could set whether to start a video in a playlist as this can have unwanted side effects, like activating the SPA function of youtube.

(SPA = Single Page Application, for example, ensures that when I call the start page via the youtube logo that the video continues to run.)

**Describe the solution you'd like**
Just create a regex rule which (if the setting is active) removes the key value entry named "list" in the GET parameters so that only the video is called without the list.

**Describe alternatives you've considered**
The manual removal is nerdy.

**Additional context**
n/a

**Comment by NikkelM** [comment]
That sounds like a very reasonable idea. I hand't even noticed that starting a playlist influences this behaviour. I'll take a look at getting this into one of the next releases.
