### ISSUE TITLE
BUG api error  (403 ) 

### ISSUE THREAD

**Issue by Autounit777** [NikkelM/Random-YouTube-Video#91]
Please help  api error  (403 )

**Comment by NikkelM** [comment]
Hi, there currently is a problem with the API, I'm sorry about that. This will be fixed with the next update, as soon as it is approved by Google and distributed in the store (which normally takes 1-2 days)!

**Comment by Autounit777** [comment]
thanks for the quick reply. i will wait for updates. using your app every day.

good luck & thx

**Comment by NikkelM** [comment]
The update has already been approved & is now available. Please check if your installed extension has version 1.2.1 and it should work again. Enjoy!

**Comment by Autounit777** [comment]
everything works correctly. thank you for the quick update.
